### ISSUE TITLE
Access to the EEG data

### ISSUE THREAD

**Issue by abrahama976** [marvinmouroum/End-to-End-EEG-Classifier#1]
The code when executed has an issue in  retrieving the data.

Hence facing the error as follows:

adc.json  gdrive  sample_data
creating directory
 gdrive/My\ Drive/DeepLearning/VideoBatches/subject6
mkdir: cannot create directory ‘gdrive/My Drive/DeepLearning/VideoBatches/subject6’: No such file or directory
creating data for  train6.mat
loading file:
 1v8RaiTYN82BUJuOXIeJH5YvUWP42ZyNc
---------------------------------------------------------------------------
HttpError                                 Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/pydrive/files.py in FetchMetadata(self, fields, fetch_all)
    236                                                  fields=fields)\
--> 237           .execute(http=self.http)
    238       except errors.HttpError as error:

8 frames
HttpError: <HttpError 404 when requesting https://www.googleapis.com/drive/v2/files/1v8RaiTYN82BUJuOXIeJH5YvUWP42ZyNc?alt=json returned "File not found: 1v8RaiTYN82BUJuOXIeJH5YvUWP42ZyNc". Details: "File not found: 1v8RaiTYN82BUJuOXIeJH5YvUWP42ZyNc">

During handling of the above exception, another exception occurred:

ApiRequestError                           Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/pydrive/files.py in FetchMetadata(self, fields, fetch_all)
    237           .execute(http=self.http)
    238       except errors.HttpError as error:
--> 239         raise ApiRequestError(error)
    240       else:
    241         self.uploaded = True

ApiRequestError: <HttpError 404 when requesting https://www.googleapis.com/drive/v2/files/1v8RaiTYN82BUJuOXIeJH5YvUWP42ZyNc?alt=json returned "File not found: 1v8RaiTYN82BUJuOXIeJH5YvUWP42ZyNc". Details: "File not found: 1v8RaiTYN82BUJuOXIeJH5YvUWP42ZyNc"> 

Kindly help. Thanks

**Comment by marvinmouroum** [comment]
Hello,

glad to see that you are interested in EEG data classification.

You can create the data set yourself. As written in the ReadMe, the used data set is provided by:

Murat Kaya, Mustafa Kemal Binli, Erkan Ozbay, Hilmi Yanar, and Yuriy Mishchenko. A large electroencephalographic motor imagery dataset for electroencephalographic brain computer interfaces. Scientific Data, 5:180211, 10 2018. doi: 10.1038/sdata.2018.211.

You can fetch the data from the original source. The the 3D representation of the data is described in the ReadMe as well and should be present in the code.

Good luck

**Comment by abrahama976** [comment]
Hi Sir,
Thankyou so much for getting back. As you have mentioned we have taken the data now.
